
services:
  postgres:
    ports:
      - "5432:5432"   # Expose ra ngoài để dùng DBeaver / pgAdmin
    restart: "no"

  app:
    ports:
      - "8080:8080"   # Truy cập trực tiếp, không qua Nginx
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JAVA_TOOL_OPTIONS=-Xmx512m -Xms256m
    restart: "no"
