spring.application.name=StockSpace_BE

# ==================== PostgresSQL ====================
spring.datasource.url=jdbc:postgresql://localhost:5432/stockspace
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================== JPA / Hibernate ====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==================== JWT ====================
app.jwt.secret=yMEh4Ugu-AjLamFpAHVTpDn-l2qlcQQNK98L3YTByH28Abs73PuhboCzQQK6mY365L-i0s6_hAPN__vaGmXRYQ
app.jwt.expiration-ms=86400000
# 86400000ms = 24 hours
app.jwt.refresh-expiration-ms=604800000
# 604800000ms = 7 days

# ==================== Server ====================
server.port=8080
