# =========================================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.fu.stockspace=DEBUG
logging.level.org.springframework.security=INFO

spring.jpa.hibernate.ddl-auto=update
